version: '3.8'

services:
  app:
    build:
      context: .
    command: bash start-test.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
      SPRING_PROFILES_ACTIVE: test
    volumes:
      - .:/reactive-flashcards
      - box:/box
  box:
    image: busybox
    volumes:
      - /box
volumes:
  box: